language: elixir
elixir:
  - 1.4.5
  - 1.5.0
otp_release:
  - 19.3
  - 20.0
sudo: false
before_script:
  - export MIX_ENV=test
  - export APP_NAME=giraphe
  # Install dialyxir
  - git clone https://github.com/jeremyjh/dialyxir.git
  - cd dialyxir
  - MIX_ENV=prod mix do compile, archive.build
  - MIX_ENV=prod mix archive.install --force
  - cd ..
  # Download and stage pre-built PLT
  - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  - export PLT_TESTNAME=dialyxir_erlang-${TRAVIS_OTP_RELEASE}_elixir-${TRAVIS_ELIXIR_VERSION}_deps-${MIX_ENV}.plt
  - export PLT_LOCATION=_build/$MIX_ENV/$PLT_TESTNAME
  - mkdir -p _build/$MIX_ENV
  - wget -O $PLT_LOCATION https://raw.github.com/jonnystorm/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test
  - mix dialyzer --halt-exit-status

